# Generated by Django 4.1.5 on 2023-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositos', '0002_alter_propositos_fechaconseguido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositos',
            name='fechaConseguido',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='propositos',
            name='fechaObjetivo',
            field=models.DateTimeField(),
        ),
    ]
