# Generated by Django 4.1.5 on 2023-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositos', '0003_alter_propositos_fechaconseguido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositos',
            name='fechaObjetivo',
            field=models.DateField(),
        ),
    ]
