# Generated by Django 4.1.5 on 2023-01-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recetario',
            new_name='Recetas',
        ),
    ]
