# Generated by Django 4.1.5 on 2023-01-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0004_alter_categoria_options_alter_receta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.ManyToManyField(to='recetario.categoria', verbose_name='categorias'),
        ),
    ]
