# Generated by Django 4.1.6 on 2023-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaEmpresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='personaContacto',
            field=models.CharField(max_length=255, verbose_name='Persona de contacto'),
        ),
    ]
