# Generated by Django 4.1.6 on 2023-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaEmpresas', '0002_alter_empresa_personacontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
    ]
